---
- name: Install package
  apt:
    name: '{{ package }}'
    state: present

- name: Fetch application on git
  git:
    repo: '{{ repository }}'
    dest: '{{ workdir }}'

- name: Package webapp
  shell: mvn clean package
  args:
    chdir: '{{ workdir }}'

- name: Synchronize war-file
  synchronize:
    mode: pull
    src: '{{ workdir }}/target/hello-1.0.war'
    dest: '{{ workdir }}/hello-1.0.war'

- name: Clear source
  file:
    state: absent
    path: '{{ workdir }}'
